# Generated by Django 3.0.1 on 2019-12-31 06:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('inst_type', models.CharField(choices=[('APri', 'Private Academic'), ('APub', 'Public Academic'), ('IRes', 'Industry Research'), ('IApp', 'Industry Applied')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('arxiv', models.CharField(max_length=200)),
                ('poster', models.CharField(max_length=200)),
                ('video', models.CharField(max_length=200)),
                ('github', models.CharField(max_length=200)),
                ('slides', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('conf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neurips_2019.Conference')),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neurips_2019.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='Authored_by',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neurips_2019.Author')),
                ('conf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neurips_2019.Conference')),
                ('institution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neurips_2019.Institution')),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neurips_2019.Topic')),
            ],
        ),
    ]
